### ISSUE TITLE
[README Request] Custom Types JSON

### ISSUE THREAD

**Issue by diederikproot** [margueriteroth/gatsby-prismic-starter-prist#2]
Hello,

can you add the JSON structure of the custom prismic types in the README?
This would make it easier to reproduce the prismic configuration.

Thank you.

Awsome starter btw

**Comment by pccunny** [comment]
Thank you for your quick reply.

Yes i did but it is from pictures and not code so checking I have the 
same as the code does not compile with my resp..it does with starter 
repo. The readme does not mention a type id for about_link but it is 
shown and in the Graphql.

Did i miss anything in the Main page content type as the error about_

" ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Field "about_link" of type "PRISMIC__Linkable" must have a selection of 
subfields. Did you mean "about_link { ... }"?

Many thanks

Regards Paul, Email Signature
Logo <https://pcconsultingasia.com> 	
*Paul Cunliffe*
Phone: 	*0878957026*
Mobile: 	*+66 878957026*
Email: 	*paul@pcconsultingasia.com*
Website: 	*pcconsultingasia.com* <http://pcconsultingasia.com>
Address: 	*PC Consulting Asia**, 120/3 Thepkasattri Road Srisoonthorn, 
Thalang Phuket 83110**, Thailand*

facebook icon <https://www.facebook.com/seoservicephuket/> twitter icon 
<https://twitter.com/phuket_seo> linkedin icon 
<https://www.linkedin.com/in/paul-cunliffe/> instagram icon 
<https://www.instagram.com/phuketseo/>

The content of this email is confidential and intended for the recipient 
specified in message only. It is strictly forbidden to share any part of 
this message with any third party, without a written consent of the 
sender. If you received this message by mistake, please reply to this 
message and follow with its deletion, so that we can ensure such a 
mistake does not occur in the future.

**Comment by margueriteroth** [comment]
Sorry for the confusion! Custom type JSON added to the README. @pccunny @diederikproot
